steps:
# Step 1: Unit Test
- id: 'Unit Test'
  name: gcr.io/alert-flames-286515/pythonbaseimage:v23
  entrypoint: python3
  args:
  - test_app.py

# Step 1: Build the Docker image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/signup-python-app:latest', '.']


# Step 2: Push the Docker image to Google Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/signup-python-app:latest']

options:
  logging : CLOUD_LOGGING_ONLY
timeout: 1600s